### PR TITLE
Fix refreshing tokens

### PR DESCRIPTION
**Pull request by WouterSioen**

### CODE REVIEW

**Comment by WouterSioen** [comment]
@

**Comment by WouterSioen** [comment]
this does not work yet, I'll work this out further

**Comment by WouterSioen** [comment]
fully fixed now :)

**Comment by turanct** [comment]
thanks!

i like my branch names structured (going to add `CONTRIBUTING.md`)
- bugfix-xxx
- feature-xxx
- release-xxx

where `xxx` is to be replaced with a reasonable reference to what you did

so would be nice to do this for future branches

**Pull request merged**
